apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  REDIS_HOST: "redis-service.default.svc.cluster.local"
  REDIS_PORT: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: vguidi/fastapi_k8s_demo:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: inventory-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - port: 8000
      targetPort: 8000